[package]
name = "block-pseudorand"
description = "Generator of random Vec<T>'s for types that can be transmuted from arbitrary bytes."
version = "0.1.2"
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
chiapos-chacha8 = "0.1.0"
nanorand = "0.6.1"
